---
apiVersion: batch/v1
kind: Job
metadata:
  name: cray-product-catalog-restore
  namespace: services
  annotations:
    "helm.sh/hook": post-upgrade,post-rollback
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: cray-product-catalog
      restartPolicy: Never
      containers:
      - name: create-catalog-configmap
        image: "{{ .Values.kubectl.image.registry }}/{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
        command: ["/bin/sh"]
        args:
        - -c
        - "kubectl get cm -n services cpc-backup -o yaml --export | sed 's/^\\s*name: cpc-backup/  name: cray-product-catalog/' | kubectl apply -f - && kubectl delete cm -n services cpc-backup"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cray-product-catalog-backup
  namespace: services
  annotations:
    "helm.sh/hook": pre-upgrade,pre-rollback
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: cray-product-catalog
      restartPolicy: Never
      containers:
      - name: create-catalog-configmap
        image: "{{ .Values.kubectl.image.registry }}/{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
        command: ["/bin/sh"]
        args:
        - -c
        - "kubectl get cm -n services cray-product-catalog -o yaml --export | sed 's/^\\s*name: cray-product-catalog/  name: cpc-backup/' | kubectl apply -f -"
